artifact_uri: sqlite/1/4e2d88a4506d4be8b6d61eb5f20a173f/artifacts
end_time: 1658136377789
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4e2d88a4506d4be8b6d61eb5f20a173f
run_uuid: 4e2d88a4506d4be8b6d61eb5f20a173f
source_name: ''
source_type: 4
source_version: ''
start_time: 1658136377387
status: 4
tags: []
user_id: rafael.pierre
